### ISSUE TITLE
Highlights are offset incorrectly on zoom

### ISSUE THREAD

**Issue by pgeske** [mistic100/jquery-highlighttextarea#50] opened 2015-03-23 18:07 UTC
Hello,
Highlighting words in my text area works fine when the zoom level is set to 100%. However, if I try doing the same thing while zoomed in, the correct words are not highlighted, because the highlights seem to be offset incorrectly when the zoom level is not 100%. Is there any fix to this problem? I noticed this on the website (http://mistic100.github.io/jquery-highlighttextarea/) as well; if you zoom in at 125%, reload, and look at the first text area example, you should see that the highlights are offset.

**Comment by mistic100** [comment] 2015-03-23 18:40
duplicate of #32 
also see the development status in the readme

**Closed by mistic100** 2015-03-23 18:40 UTC
